# Generated by Django 4.2.15 on 2024-08-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
